### ISSUE TITLE
Exception shown in the logs when node_agent can't find job queue in etcd

### ISSUE THREAD

**Issue by GowthamShanmugam** [Tendrl/node_agent#94]
2016-12-08T21:18:51+0000 - rpc.py:160 -                 _run() - ERROR - Traceback (most recent call last):
  File "/usr/lib/python2.7/site-packages/tendrl_node_agent-0.0.1-py2.7.egg/tendrl/node_agent/manager/rpc.py", line 158, in _run
    self._server.run()
  File "/usr/lib/python2.7/site-packages/tendrl_node_agent-0.0.1-py2.7.egg/tendrl/node_agent/manager/rpc.py", line 81, in run
    self._acceptor()
  File "/usr/lib/python2.7/site-packages/tendrl_node_agent-0.0.1-py2.7.egg/tendrl/node_agent/manager/rpc.py", line 59, in _acceptor
    jobs = self.client.read("/queue")
  File "/usr/lib/python2.7/site-packages/python_etcd-0.4.3-py2.7.egg/etcd/client.py", line 536, in read
    timeout=timeout)
  File "/usr/lib/python2.7/site-packages/python_etcd-0.4.3-py2.7.egg/etcd/client.py", line 848, in wrapper
    return self._handle_server_response(response)
  File "/usr/lib/python2.7/site-packages/python_etcd-0.4.3-py2.7.egg/etcd/client.py", line 928, in _handle_server_response
    etcd.EtcdError.handle(r)
  File "/usr/lib/python2.7/site-packages/python_etcd-0.4.3-py2.7.egg/etcd/__init__.py", line 304, in handle
    raise exc(msg, payload)
EtcdKeyNotFound: Key not found : /queue

Instead of the exception, node_agent should validate the data it's getting from etcd and log the issue properly without raising the exception.

**Comment by mbukatov** [comment]
Looks related to https://github.com/Tendrl/gluster_integration/issues/26 - it's a different bug, but of the same kind.

**Comment by GowthamShanmugam** [comment]
@mbukatov  yes both are same kind

**Comment by TimothyAsir** [comment]
This will be completely addressed once the spec resolved
https://github.com/Tendrl/specifications/issues/57

**Comment by mbukatov** [comment]
Why is this issue closed when I still see it when I install tendrl-node-agent from current master (commit 39d2dfecc4c40b48d9c9bddc0e71d99dac7abfdc)?

I understand that fix is blocked by a work on given specification, but until the fix is actually merged in the master branch, closing the issue seems a bit misleading.

## Evidence

```
# systemctl status tendrl-noded
● tendrl-noded.service - A python agent local to every managed storage node in the sds cluster
   Loaded: loaded (/etc/systemd/system/tendrl-noded.service; enabled; vendor preset: disabled)
   Active: failed (Result: start-limit) since Tue 2016-12-20 16:11:18 UTC; 7min ago
 Main PID: 31896 (code=exited, status=1/FAILURE)

Dec 20 16:11:18 mbukatov-usm5-node1.example.com systemd[1]: tendrl-noded.service: main process exited, code=exited, status=1/FAILURE
Dec 20 16:11:18 mbukatov-usm5-node1.example.com systemd[1]: Unit tendrl-noded.service entered failed state.
Dec 20 16:11:18 mbukatov-usm5-node1.example.com systemd[1]: tendrl-noded.service failed.
Dec 20 16:11:18 mbukatov-usm5-node1.example.com systemd[1]: tendrl-noded.service holdoff time over, scheduling restart.
Dec 20 16:11:18 mbukatov-usm5-node1.example.com systemd[1]: start request repeated too quickly for tendrl-noded.service
Dec 20 16:11:18 mbukatov-usm5-node1.example.com systemd[1]: Failed to start A python agent local to every managed storage node in th...uster.
Dec 20 16:11:18 mbukatov-usm5-node1.example.com systemd[1]: Unit tendrl-noded.service entered failed state.
Dec 20 16:11:18 mbukatov-usm5-node1.example.com systemd[1]: tendrl-noded.service failed.
Hint: Some lines were ellipsized, use -l to show in full.
```

```
# journalctl -u tendrl-noded.service
-- Logs begin at Tue 2016-12-20 15:45:45 UTC, end at Tue 2016-12-20 16:12:57 UTC. --
Dec 20 16:11:14 mbukatov-usm5-node1.example.com systemd[1]: Started A python agent local to every managed storage node in the sds cluster.
Dec 20 16:11:14 mbukatov-usm5-node1.example.com systemd[1]: Starting A python agent local to every managed storage node in the sds cluster...
Dec 20 16:11:15 mbukatov-usm5-node1.example.com tendrl-node-agent[31796]: Traceback (most recent call last):
Dec 20 16:11:15 mbukatov-usm5-node1.example.com tendrl-node-agent[31796]: File "/usr/bin/tendrl-node-agent", line 11, in <module>
Dec 20 16:11:15 mbukatov-usm5-node1.example.com tendrl-node-agent[31796]: load_entry_point('tendrl-node-agent==0.0.1', 'console_scripts', 'te
Dec 20 16:11:15 mbukatov-usm5-node1.example.com tendrl-node-agent[31796]: File "/usr/lib/python2.7/site-packages/pkg_resources/__init__.py", 
Dec 20 16:11:15 mbukatov-usm5-node1.example.com tendrl-node-agent[31796]: return get_distribution(dist).load_entry_point(group, name)
Dec 20 16:11:15 mbukatov-usm5-node1.example.com tendrl-node-agent[31796]: File "/usr/lib/python2.7/site-packages/pkg_resources/__init__.py", 
Dec 20 16:11:15 mbukatov-usm5-node1.example.com tendrl-node-agent[31796]: return ep.load()
Dec 20 16:11:15 mbukatov-usm5-node1.example.com tendrl-node-agent[31796]: File "/usr/lib/python2.7/site-packages/pkg_resources/__init__.py", 
Dec 20 16:11:15 mbukatov-usm5-node1.example.com tendrl-node-agent[31796]: return self.resolve()
Dec 20 16:11:15 mbukatov-usm5-node1.example.com tendrl-node-agent[31796]: File "/usr/lib/python2.7/site-packages/pkg_resources/__init__.py", 
Dec 20 16:11:15 mbukatov-usm5-node1.example.com tendrl-node-agent[31796]: module = __import__(self.module_name, fromlist=['__name__'], level=
Dec 20 16:11:15 mbukatov-usm5-node1.example.com tendrl-node-agent[31796]: File "/usr/lib/python2.7/site-packages/tendrl/node_agent/manager/ma
Dec 20 16:11:15 mbukatov-usm5-node1.example.com tendrl-node-agent[31796]: from tendrl.common.log import setup_logging
Dec 20 16:11:15 mbukatov-usm5-node1.example.com tendrl-node-agent[31796]: File "/usr/lib/python2.7/site-packages/tendrl/common/log.py", line 
Dec 20 16:11:15 mbukatov-usm5-node1.example.com tendrl-node-agent[31796]: config.get('common', 'log_level')
Dec 20 16:11:15 mbukatov-usm5-node1.example.com tendrl-node-agent[31796]: File "/usr/lib/python2.7/site-packages/tendrl/common/log.py", line 
Dec 20 16:11:15 mbukatov-usm5-node1.example.com tendrl-node-agent[31796]: raise Exception("logging configuration not found")
Dec 20 16:11:15 mbukatov-usm5-node1.example.com tendrl-node-agent[31796]: Exception: logging configuration not found
Dec 20 16:11:15 mbukatov-usm5-node1.example.com systemd[1]: tendrl-noded.service: main process exited, code=exited, status=1/FAILURE
Dec 20 16:11:15 mbukatov-usm5-node1.example.com systemd[1]: Unit tendrl-noded.service entered failed state.
Dec 20 16:11:15 mbukatov-usm5-node1.example.com systemd[1]: tendrl-noded.service failed.
Dec 20 16:11:15 mbukatov-usm5-node1.example.com systemd[1]: tendrl-noded.service holdoff time over, scheduling restart.
Dec 20 16:11:15 mbukatov-usm5-node1.example.com systemd[1]: Started A python agent local to every managed storage node in the sds cluster.
Dec 20 16:11:15 mbukatov-usm5-node1.example.com systemd[1]: Starting A python agent local to every managed storage node in the sds cluster...
Dec 20 16:11:16 mbukatov-usm5-node1.example.com tendrl-node-agent[31854]: Traceback (most recent call last):
Dec 20 16:11:16 mbukatov-usm5-node1.example.com tendrl-node-agent[31854]: File "/usr/bin/tendrl-node-agent", line 11, in <module>
Dec 20 16:11:16 mbukatov-usm5-node1.example.com tendrl-node-agent[31854]: load_entry_point('tendrl-node-agent==0.0.1', 'console_scripts', 'te
Dec 20 16:11:16 mbukatov-usm5-node1.example.com tendrl-node-agent[31854]: File "/usr/lib/python2.7/site-packages/pkg_resources/__init__.py", 
Dec 20 16:11:16 mbukatov-usm5-node1.example.com tendrl-node-agent[31854]: return get_distribution(dist).load_entry_point(group, name)
Dec 20 16:11:16 mbukatov-usm5-node1.example.com tendrl-node-agent[31854]: File "/usr/lib/python2.7/site-packages/pkg_resources/__init__.py", 
Dec 20 16:11:16 mbukatov-usm5-node1.example.com tendrl-node-agent[31854]: return ep.load()
Dec 20 16:11:16 mbukatov-usm5-node1.example.com tendrl-node-agent[31854]: File "/usr/lib/python2.7/site-packages/pkg_resources/__init__.py", 
Dec 20 16:11:16 mbukatov-usm5-node1.example.com tendrl-node-agent[31854]: return self.resolve()
Dec 20 16:11:16 mbukatov-usm5-node1.example.com tendrl-node-agent[31854]: File "/usr/lib/python2.7/site-packages/pkg_resources/__init__.py", 
Dec 20 16:11:16 mbukatov-usm5-node1.example.com tendrl-node-agent[31854]: module = __import__(self.module_name, fromlist=['__name__'], level=
Dec 20 16:11:16 mbukatov-usm5-node1.example.com tendrl-node-agent[31854]: File "/usr/lib/python2.7/site-packages/tendrl/node_agent/manager/ma
Dec 20 16:11:16 mbukatov-usm5-node1.example.com tendrl-node-agent[31854]: from tendrl.common.log import setup_logging
Dec 20 16:11:16 mbukatov-usm5-node1.example.com tendrl-node-agent[31854]: File "/usr/lib/python2.7/site-packages/tendrl/common/log.py", line 
Dec 20 16:11:16 mbukatov-usm5-node1.example.com tendrl-node-agent[31854]: config.get('common', 'log_level')
Dec 20 16:11:16 mbukatov-usm5-node1.example.com tendrl-node-agent[31854]: File "/usr/lib/python2.7/site-packages/tendrl/common/log.py", line 
Dec 20 16:11:16 mbukatov-usm5-node1.example.com tendrl-node-agent[31854]: raise Exception("logging configuration not found")
Dec 20 16:11:16 mbukatov-usm5-node1.example.com tendrl-node-agent[31854]: Exception: logging configuration not found
Dec 20 16:11:16 mbukatov-usm5-node1.example.com systemd[1]: tendrl-noded.service: main process exited, code=exited, status=1/FAILURE
Dec 20 16:11:16 mbukatov-usm5-node1.example.com systemd[1]: Unit tendrl-noded.service entered failed state.
Dec 20 16:11:16 mbukatov-usm5-node1.example.com systemd[1]: tendrl-noded.service failed.

```

**Comment by shtripat** [comment]
Looking at exception I see that log configuration for tendrl node agent service is not found. Can you verify if /etc/tendrl/node_agent_logging.yaml is available in your setup and the same is referred correctly in /etc/tendrl/tendrl.conf file's [node_agent] section as below

```
[node_agent]
# Path to log file
log_level = DEBUG
tendrl_exe_file_prefix = /tmp/.tendrl_runner
log_cfg_path = /etc/tendrl/node_agent_logging.yaml
```
